---
- hosts: all
  sudo: yes
  tasks:
  - name: Add Percona Repo Key
    apt_key: keyserver=keys.gnupg.net id=1C4CBDCDCD2EFD2A state=present
  - name: Add Percona Repo Source
    apt_repository: repo='{{ item }}' state=present
    with_items:
      - "deb http://repo.percona.com/apt trusty main"
      - "deb-src http://repo.percona.com/apt trusty main"

- hosts: small-nodes
  vars:
    mysql_version: 5.5
  sudo: yes
  tasks:
  - name: Install Percona Server
    apt: name={{ item }} state=present
    with_items:
      - percona-server-server-{{ mysql_version }} 
    notify:
    - mysql running

  handlers:
  - name: mysql running
    service: name=mysql state=started
