---
- include: percona-repo.yml

- hosts: small-nodes
  vars:
    mysql_version: 5.5
  sudo: yes
  tasks:
  - name: Install Percona Server
    apt: name={{ item }} state=present
    with_items:
      - percona-server-server-{{ mysql_version }} 
    notify:
    - mysql running

  handlers:
  - name: mysql running
    service: name=mysql state=started
